version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/Frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/Backend"
    schedule:
      interval: "daily"
