version: "2"

linters:
  enable:
    - staticcheck
    - bodyclose
    - errcheck
    - rowserrcheck
    - exhaustive
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - nolintlint
    - unconvert
    - unparam
    - unused
    - prealloc
    - predeclared
    - asciicheck
    - makezero
    - dupl
    - errname
    - sqlclosecheck
    - sloglint

run:
  tests: true
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  uniq-by-line: true
  fix: true

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
    - gofmt


