version: 2
project_name: QuickNote
builds:
  - id: QuickNote
    main: ./main.go
    binary: QuickNote
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
      - -tags=mysql postgres sqlite sqlserver
    asmflags:
      - -trimpath
    gcflags:
      - all=-d=ssa/check_bce/debug=0
    ldflags:
      - -s -w -buildid=
      - -extldflags=-static
      - -linkmode internal
      - -X github.com/Sn0wo2/QuickNote/pkg/version.version={{.Version}}
      - -X github.com/Sn0wo2/QuickNote/pkg/version.commit={{.Commit}}
      - -X github.com/Sn0wo2/QuickNote/pkg/version.date={{.Date}}
archives:
  - id: default
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: ./README.md
        dst: README.md
      - src: ./data/config.yml
        dst: data/config.yml
      - src: ./LICENSE
        dst: LICENSE
      - src: ./Frontend/static
        dst: static

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "me0wo/quicknote:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - data/config.yml
      - Frontend/static

  - goos: linux
    goarch: arm64
    image_templates:
      - "me0wo/quicknote:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    extra_files:
      - data/config.yml
      - Frontend/static

docker_manifests:
  - name_template: "me0wo/quicknote:{{ .Tag }}"
    image_templates:
      - "me0wo/quicknote:{{ .Tag }}-amd64"
      - "me0wo/quicknote:{{ .Tag }}-arm64"
  - name_template: "me0wo/quicknote:latest"
    image_templates:
      - "me0wo/quicknote:{{ .Tag }}-amd64"
      - "me0wo/quicknote:{{ .Tag }}-arm64"
changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: "🚀 Features"
      regexp: "^.*feat(?:\\([^)]+\\))?:+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix(?:\\([^)]+\\))?:+.*$"
      order: 1
    - title: "⚡️ Performance Improvements"
      regexp: "^.*perf(?:\\([^)]+\\))?:+.*$"
      order: 2
    - title: "📝 Documentation"
      regexp: "^.*docs(?:\\([^)]+\\))?:+.*$"
      order: 3
    - title: "🔧 Maintenance & Chores"
      regexp: "^.*chore(?:\\([^)]+\\))?:+.*$"
      order: 4
    - title: "♻️ Code Refactoring"
      regexp: "^.*refactor(?:\\([^)]+\\))?:+.*$"
      order: 5
    - title: "🧪 Tests"
      regexp: "^.*test(?:\\([^)]+\\))?:+.*$"
      order: 6
    - title: "📦 Dependency Updates"
      regexp: "^.*deps(?:\\([^)]+\\))?:+.*$"
      order: 7
    - title: "📍 Others"
      order: 999
