version: 2
project_name: QuickNote
builds:
  - id: QuickNote
    main: ./main.go
    binary: QuickNote
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
      - -tags=mysql postgres sqlite sqlserver
    asmflags:
      - -trimpath
    gcflags:
      - all=-d=ssa/check_bce/debug=0
    ldflags:
      - -s -w -buildid=
      - -extldflags=-static
      - -linkmode internal
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
archives:
  - id: default
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: ./README.md
        dst: README.md
      - src: ./config.yml
        dst: config.yml
      - src: ./LICENSE
        dst: LICENSE
      - src: ./Frontend/static
        dst: static

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "me0wo/quicknote:{{ .Tag }}-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    extra_files:
      - config.yml
      - Frontend/static

  - goos: linux
    goarch: arm64
    image_templates:
      - "me0wo/quicknote:{{ .Tag }}-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    extra_files:
      - config.yml
      - Frontend/static

docker_manifests:
  - name_template: "me0wo/quicknote:{{ .Tag }}"
    image_templates:
      - "me0wo/quicknote:{{ .Tag }}-amd64"
      - "me0wo/quicknote:{{ .Tag }}-arm64"
  - name_template: "me0wo/quicknote:latest"
    image_templates:
      - "me0wo/quicknote:{{ .Tag }}-amd64"
      - "me0wo/quicknote:{{ .Tag }}-arm64"
changelog:
  disable: false
  use: github
  sort: asc
  groups:
    - title: 🚀 New Features
      regexp: "^.*feat(\\w*):+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix(\\w*):+.*$"
      order: 1
    - title: "⚡️ Performance"
      regexp: "^.*perf(\\w*):+.*$"
      order: 2
    - title: "📝 Documentation"
      regexp: "^.*docs(\\w*):+.*$"
      order: 3
    - title: "🔧 Enhancements"
      regexp: "^.*chore(\\w*):+.*$"
      order: 4
    - title: "♻️ Refactor"
      regexp: "^.*refactor(\\w*):+.*$"
      order: 5
    - title: "🧪 Tests"
      regexp: "^.*test(\\w*):+.*$"
      order: 6
    - title: "📦 Dependencies"
      regexp: "^.*deps(\\w*):+.*$"
      order: 7
    - title: 📍 Others
      order: 999