name: 'CI/CD'

on: [push, pull_request, workflow_dispatch]

jobs:
  setup:
    name: Setup and Install
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install latest Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'

      - name: Cache Bun dependencies
        uses: actions/cache@main
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

  lint:
    name: Lint and Format
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install latest Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'

      - name: Run ESLint
        run: eslint .

      - name: Run Prettier Check
        run: prettier --check .

  security:
    name: Security Audit
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Install latest Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'

      - name: Run security audit
        run: |
          bun audit
