name: 'CI/CD'

on: [push, pull_request, workflow_dispatch]

env:
  NODE_VERSION: '22'
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  npm:
    name: install dependencies (npm)
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@main

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install node dependencies
        run: npm i

  es-lint:
    name: check linting (es-lint)
    needs: [npm]
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@main

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install node dependencies
        run: npm i

      - name: Check ESlint
        run: npm run lint

  prettier:
    name: check format (prettier)
    needs: [npm]
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install node dependencies
        run: npm i

      - name: Check Prettier
        run: npm run format:fix

      - name: Commit prettier changes
        if: ${{ !github.head_ref }}
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "style: make prettier happy"

      - name: Create commit lint change pr
        if: ${{ !github.head_ref }}
        continue-on-error: true
        uses: peter-evans/create-pull-request@main
