name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  setup:
    name: Setup and Install
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install latest Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

  lint:
    name: Lint and Format
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install latest Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'

      - name: Run ESLint
        run: bun run lint

      - name: Run Prettier Check
        run: bun run format -- --check

      - name: Auto-fix and commit formatting
        if: github.ref == 'refs/heads/main' && !github.event.pull_request
        run: |
          bun run format
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "style: make prettier happy" && git push)

      - name: Create Prettier Fix PR
        if: github.ref != 'refs/heads/main' && !github.event.pull_request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "style: make prettier happy"
          title: "style: Prettier formatting fixes"
          body: "Automated formatting fixes from Prettier"
          branch: "prettier-fixes/${{ github.run_id }}"
          delete-branch: true
