name: Go CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.github/workflows/go.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-test-vet:
    name: Build, Test & Vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Dependencies
        run: go mod tidy

      - name: Test
        run: go test -vet=off $(go list ./...)

      - name: Vet
        run: go vet $(go list ./...)

      - name: Build
        run: |
          mkdir -p dist
          go build -v -o dist/QuickNote .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickNote Artifact
          path: dist/QuickNote

  lint-and-fix:
    name: Go Lint and Auto-fix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run golangci-lint with auto-fix
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --fix
          cache-key: golangci-lint
          cache: true

      - name: Check for file changes
        id: git-check
        run: |
          if git diff --exit-code; then
            echo "No changes from linter."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Linter made changes."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request with lint fixes
        if: steps.git-check.outputs.changed == 'true' && github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(backend): fix lint issues"
          title: "Fix: Apply Go linting fixes"
          body: "The `golangci-lint` action wants to apply these fixes."
          branch: "chore/go-lint-fixes"
          base: main
          signoff: true
          sign-commits: true
          reviewers: "Sn0wo2"
          labels: "bot,lint"