name: React CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Frontend/**'
      - '.github/workflows/react.yml'
  pull_request:
    paths:
      - 'Frontend/**'
      - '.github/workflows/react.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    working-directory: Frontend

jobs:
  lint-and-fix:
    name: Frontend Lint and Auto-fix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint with auto-fix
        run: bun run lint:fix

      - name: Check for file changes
        id: git-check
        working-directory: .
        run: |
          if git diff --exit-code; then
            echo "No changes from linter."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Linter made changes."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request with lint fixes
        if: steps.git-check.outputs.changed == 'true' && github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(frontend): fix lint issues"
          title: "Fix: Apply React linting fixes"
          body: "The `ESLint` action wants to apply these fixes."
          branch: "chore/es-lint-fixes"
          base: main
          signoff: true
          sign-commits: true
          reviewers: "Sn0wo2"
          labels: "bot,lint"